site_name: mkdocs-demo
site_description: Voorbeeld MkDocs project met automatische inrichting
site_author: Ruud Hirschmann
repo_url: https://github.com/rhirschmann/mkdocs-demo
theme:
  name: material

extra:
  version: 0.1.0
  created: 20-05-2026

theme:
  name: material
  language: nl
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Donkere modus
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
      - Introductie: getting-started/index.md
      - Installatie: getting-started/install.md
  - Over: about/index.md

plugins:
  - search
  - tags
  - social
